version: 0.2
phases:
  pre_build:
    commands:
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_URI
      - docker pull $IMAGE_CACHE || true
  build:
    commands:
      - docker build --cache-from $IMAGE_CACHE -t $IMAGE -t $IMAGE_CACHE .
  post_build:
    commands:
      - docker push $IMAGE
      - docker push $IMAGE_CACHE
